drop table if exists mydb.ticket;


CREATE TABLE mydb.ticket (
	TICKETID int NOT NULL AUTO_INCREMENT,
	PNR VARCHAR(100) NOT NULL UNIQUE,
	BOOKINGDATE DATETIME NOT NULL,
	ISROUNDTRIP VARCHAR(1), 
	ISMEALREQUIRED VARCHAR(1),
	ROUTEID int, 
    BOOKINGSTATUS VARCHAR(25) NOT NULL,
    TICKETSTATUS VARCHAR(25) NOT NULL,
    CUSTOMEREMAIL VARCHAR(100) NOT NULL,
	PRIMARY KEY(TICKETID),
	FOREIGN KEY (ROUTEID) REFERENCES mydb.route(ROUTEID)
);