INSERT INTO mydb.airline (Name,Logo,status) values ('Indigo',NULL,'A');
INSERT INTO mydb.airline (Name,Logo,status) values ('SpiceJet',NULL,'A');


INSERT INTO mydb.flight (FLIGHTUUID,MODEL,AIRLINEID,status) values ('ING-001','AIRBUS',1,'A');
INSERT INTO mydb.flight (FLIGHTUUID,MODEL,AIRLINEID,status) values ('ING-002','AIRBUS',1,'A');
INSERT INTO mydb.flight (FLIGHTUUID,MODEL,AIRLINEID,status) values ('SPC-001','BOEING',1,'A');
INSERT INTO mydb.flight (FLIGHTUUID,MODEL,AIRLINEID,status) values ('SPC-002','BOEING',1,'I');


INSERT INTO mydb.route (FROMCITY,TOCITY,PRICE,FLIGHTID, DEPARTURETIME, ARRIVALTIME,STATUS) values ('Chennai','Mumbai','4500.20','1','05:00:00','06:30:00','A');
INSERT INTO mydb.route (FROMCITY,TOCITY,PRICE,FLIGHTID, DEPARTURETIME, ARRIVALTIME,STATUS) values ('Chennai','Hyderabad','7400.20','2','07:00:00','08:15:00','A');
INSERT INTO mydb.route (FROMCITY,TOCITY,PRICE,FLIGHTID, DEPARTURETIME, ARRIVALTIME,STATUS) values ('Chennai','Jaipur','12300.20','3','10:00:00','12:30:00','A');
INSERT INTO mydb.route (FROMCITY,TOCITY,PRICE,FLIGHTID, DEPARTURETIME, ARRIVALTIME,STATUS) values ('Jaipur','Chennai','6523.20','4','17:00:00','19:30:00','A');


INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI001',SYSDATE(),'N','N','1','INITIATED','CONFIRMED','abc@abc.com');
INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI002',SYSDATE(),'N','N','2','COMPLETE','WAITLIST','efg@abc.com');
INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI011',SYSDATE(),'N','N','1','COMPLETE','CONFIRMED','asd@abc.com');
INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI022',SYSDATE(),'N','N','2','COMPLETE','CONFIRMED','qwe@abc.com');
INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI003',SYSDATE(),'N','N','3','PENDING','CANCELED','ijk@abc.com');
INSERT INTO mydb.ticket (TRAVELDATE,PNR,BOOKINGDATE,ISROUNDTRIP,ISMEALREQUIRED, ROUTEID,BOOKINGSTATUS,TICKETSTATUS,CUSTOMEREMAIL) values ('2021-12-01 12:45:56','INDCHNJAI004',SYSDATE(),'N','N','1','CANCELED','CONFIRMED','lmo@abc.com');

INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('1','Pass1',25);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('2','Pass2',35);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('3','Pass3',55);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('1','Pass4',55);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('1','Pass5',65);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('3','Pass6',75);
INSERT INTO mydb.passenger (TICKETID,NAME,AGE) values ('4','Pass7',85);

