drop table if exists mydb.passenger;
drop table if exists mydb.ticket;
drop table if exists mydb.route;
drop table if exists mydb.flight;
drop table if exists mydb.airline;

CREATE TABLE mydb.airline (
    AIRLINEID int NOT NULL AUTO_INCREMENT,
    NAME varchar(255) NOT NULL,
    LOGO BLOB,
	STATUS varchar(1) NOT NULL,
	PRIMARY KEY(AIRLINEID)
);


CREATE TABLE mydb.flight (
    FLIGHTID int NOT NULL AUTO_INCREMENT,
    FLIGHTUUID varchar(255) UNIQUE,
    MODEL varchar(255),
    MAKE varchar(255),
    AIRLINEID int,
	status varchar(1) NOT NULL,
	PRIMARY KEY(FLIGHTID),
    FOREIGN KEY (AIRLINEID) REFERENCES mydb.airline(AIRLINEID)
);

CREATE TABLE mydb.route (
	ROUTEID int NOT NULL AUTO_INCREMENT,
	FROMCITY varchar(255) NOT NULL,
	TOCITY varchar(255) NOT NULL,
	PRICE DECIMAL(50,10)  NOT NULL,
	FLIGHTID int, 
	DEPARTURETIME TIME NOT NULL,
	ARRIVALTIME TIME NOT NULL,
	STATUS varchar(1) NOT NULL,
	PRIMARY KEY(ROUTEID),
	FOREIGN KEY (FLIGHTID) REFERENCES mydb.flight(FLIGHTID)
);


CREATE TABLE mydb.ticket (
	TICKETID int NOT NULL AUTO_INCREMENT,
	PNR VARCHAR(100) NOT NULL UNIQUE,
	BOOKINGDATE DATETIME NOT NULL,
	TRAVELDATE DATETIME NOT NULL,
	ISROUNDTRIP VARCHAR(1), 
	ISMEALREQUIRED VARCHAR(1),
	ROUTEID int, 
    BOOKINGSTATUS VARCHAR(25) NOT NULL,
    TICKETSTATUS VARCHAR(25) NOT NULL,
    CUSTOMEREMAIL VARCHAR(100) NOT NULL,
	PRIMARY KEY(TICKETID),
	FOREIGN KEY (ROUTEID) REFERENCES mydb.route(ROUTEID)
);

CREATE TABLE mydb.passenger (
    PASSENGERID int NOT NULL AUTO_INCREMENT,
    TICKETID int,
    NAME varchar(255),
    AGE int,
	PRIMARY KEY(PASSENGERID),
    FOREIGN KEY (TICKETID) REFERENCES mydb.ticket(TICKETID)
);